In [8]:
import torch
A = torch.zeros((2,3,4))
print(A)
A.numpy()


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [3]:
torch.ones((2,3,4,5))

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])

In [4]:
torch.randn(3,4)

tensor([[-1.0160,  0.9338, -1.5487,  1.8655],
        [ 0.8787, -1.1745, -0.5480,  1.0982],
        [ 0.4188, -1.1697,  0.2973,  0.8070]])

In [5]:
X = torch.arange(12).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
A = torch.cat((X,Y),dim = 0)
B = torch.cat((X,Y),dim = 1)



array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 2.,  1.,  4.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 4.,  3.,  2.,  1.]], dtype=float32)

In [26]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

a为3×1的矩阵，b为1×2的矩阵，执行运算操作时a会复制列，b会复制行，再进行按元素运算，使结果输出一个3×2的矩阵

In [30]:
X = torch.arange(12).reshape((3,4))
X[2,3] = 20
print(X)
X[0:2,:] = 6
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 20]])


tensor([[ 6,  6,  6,  6],
        [ 6,  6,  6,  6],
        [ 8,  9, 10, 20]])

In [32]:
X = torch.arange(12).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
before = id(Y)
Y += X
id(Y) == before

True

使用Y = Y + X会分配不必要的内存，而使用Y += X 不会(或者使用切片的操作方式，Y[:] = Y + X)

In [40]:
a = torch.tensor([3.5])
print(a)
x = a.item()
b = float(a)
c = int(a)
print(x,b,c)

tensor([3.5000])
3.5 3.5 3


In [41]:
import os

os.makedirs(os.path.join('..','data'),exist_ok= True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [42]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


NAN即为数据缺失值(待处理)

In [45]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs = inputs.fillna(inputs.mean())
print(data)
print(inputs)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [47]:
inputs = pd.get_dummies(inputs,dummy_na= True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)
prefix：str, list of str, 或 dict of str, 默认为 None
用于追加DataFrame列名称的字符串。
 
prefix_sep：str, 默认为 ‘_’
如果附加前缀，则使用分隔符/分隔符。或者像这样传递列表或字典prefix。
 
dummy_na：bool, 默认为 False
如果忽略False NaN。
 
columns：list-like, 默认为 None
要编码的DataFrame中的列名。如果columns为None，则所有具有的列object或者categorydtype将被转换。
 
sparse：bool, 默认为 False
dummy-encoded列是否应由a支持SparseArray(True)或常规NumPy数组(False)。
 
drop_first：bool, 默认为 False
是否通过删除第一个级别从k个分类级别中获取k-1个虚拟对象。

In [48]:
X = torch.tensor(inputs.to_numpy(dtype=float))
Y = torch.tensor(outputs.to_numpy(dtype=float))
print(X)
print(Y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)
tensor([127500., 106000., 178100., 140000.], dtype=torch.float64)


将inputs,outputs全部转换为张量格式，方便使用函数进行处理

In [3]:
import torch
A = torch.arange(20).reshape((4,5))
print(A)
A.T

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [3]:
import torch
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
print(A)
A * B


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

相同形状矩阵进行二元运算则按元素进行操作

In [2]:
import torch
a = 2
X = torch.arange(24).reshape(2,3,4)
print(X)
print(a + X)
(a + X).shape

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])


torch.Size([2, 3, 4])

In [17]:
A = torch.arange(12,dtype=torch.float32).reshape(3,4)
print(A)
print(A.sum())
B = A.sum()
print(B)
C = A.sum(axis = 0)
print(C)
D = A.sum(axis = 1)
print(D)
print(A.mean())
print(A.mean(axis = 0))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor(66.)
tensor(66.)
tensor([12., 15., 18., 21.])
tensor([ 6., 22., 38.])
tensor(5.5000)
tensor([4., 5., 6., 7.])


sum(axis = <轴>)为降维求和,使用后矩阵被降维成一个张量。用mean(axis = <轴>)求平均值矩阵内的元素必须为浮点型

In [22]:
A = torch.arange(12,dtype=torch.float32).reshape(3,4)
print(A)
sum_A = A.sum(axis = 0,keepdim= True)
print(sum_A)
A.cumsum(axis = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 15., 18., 21.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.]])

sum(axis = <轴数>，keepdim = true)为非降维求和，矩阵求和后任然为一个矩阵。cumsum()函数不会沿任何轴降低矩阵的维度

In [2]:
import torch
x = torch.arange(4,dtype=torch.float32)
print(X)
y = torch.ones(4,dtype=torch.float32)
print(Y)
torch.dot(x,y)

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])


tensor(6.)

In [10]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
x = torch.arange(4,dtype=torch.float32)
B = torch.ones(4,1)
print(A)
print(x)
print(B)
print(torch.mv(A,x))
print(torch.mm(A,B))


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([0., 1., 2., 3.])
tensor([[1.],
        [1.],
        [1.],
        [1.]])
tensor([ 14.,  38.,  62.,  86., 110.])
tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


torch.mv()为矩阵×向量，结果为一个向量。torch.mm()为矩阵×矩阵，结果为一个矩阵

In [12]:
u = torch.tensor([3.0,-4.0,5.0])
torch.norm(u)

tensor(7.0711)

torch.norm()求矩阵的Frobenius范数（即矩阵元素和的平方根）